{% set name = "opacus" %}
{% set version = "1.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ea700808c0a8c3fb7e565ed55b77b3170d6a54cb30e295b255e3877170edc5ca
  - url: https://raw.githubusercontent.com/pytorch/opacus/v{{ version }}/dev_requirements.txt
    sha256: 0f1427525a467cfef972dc10d7cc76d97b7c12e8a413ce4ff594b565e3004f8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.15,<2.0
    - python >={{ python_min }}
    - scipy >=1.2
    - pytorch >=1.8
    - opt_einsum >=3.3.0
    - functorch

test:
  imports:
    - opacus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://opacus.ai
  summary: Train PyTorch models with Differential Privacy
  dev_url: https://github.com/pytorch/opacus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ashkan-software
    - ffuuugor
    - karthikprasad
    - alexandresablayrolles
    - sarthakpati
